export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_QUANTITY_IN_CART = 'CHANGE_QUANTITY_IN_CART';
export const ON_LOAD = 'ON_LOAD';
export const ON_PURCHASED = 'ON_PURCHASED';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
